

IF (APIBD_GENERATORSQL_INCLUDE_DIR)
  SET(APIBD_GENERATORSQL_FIND_QUIETLY TRUE)
ENDIF (APIBD_GENERATORSQL_INCLUDE_DIR)

FIND_PATH(APIBD_GENERATORSQL_INCLUDE_DIR driver.hpp
  ${PROJECT_SOURCE_DIR}/generator-sql
  $ENV{HOME}/root/include/toolkit
  /usr/local/include/toolkit
  /usr/include/toolkit
)

SET(APIBD_GENERATORSQL_NAMES apidb-generator-sql)
FIND_LIBRARY(APIBD_GENERATORSQL_LIBRARY
  NAMES ${APIBD_GENERATORSQL_NAMES}
  PATHS ${PROJECT_SOURCE_DIR}/generator-sql ${PROJECT_SOURCE_DIR}/generator-sql $ENV{HOME}/root/usr/lib /usr/lib /usr/local/lib /usr/lib/x86_64-linux-gnu
  PATH_SUFFIXES generator-sql
)

IF (APIBD_GENERATORSQL_INCLUDE_DIR AND APIBD_GENERATORSQL_LIBRARY)
  SET(APIBD_GENERATORSQL_FOUND TRUE)
  SET( APIBD_GENERATORSQL_LIBRARIES ${APIBD_GENERATORSQL_LIBRARY} )
ELSE (APIBD_GENERATORSQL_INCLUDE_DIR AND APIBD_GENERATORSQL_LIBRARY)
  SET(APIBD_GENERATORSQL_FOUND FALSE)
  SET( APIBD_GENERATORSQL_LIBRARIES )
ENDIF (APIBD_GENERATORSQL_INCLUDE_DIR AND APIBD_GENERATORSQL_LIBRARY)

IF (APIBD_GENERATORSQL_FOUND)
  IF (NOT APIBD_GENERATORSQL_FIND_QUIETLY)
    MESSAGE(STATUS "Found apidb-generator-sql libraries: ${APIBD_GENERATORSQL_LIBRARY}")
  ENDIF (NOT APIBD_GENERATORSQL_FIND_QUIETLY)
ELSE (APIBD_GENERATORSQL_FOUND)
  IF (APIBD_GENERATORSQL_FIND_REQUIRED)
    MESSAGE(STATUS "Looked apidb-generator-sql libraries named ${APIBD_GENERATORSQL_NAMES}.")
    MESSAGE(FATAL_ERROR "Could NOT find apidb-generator-sql library")
  ENDIF (APIBD_GENERATORSQL_FIND_REQUIRED)
ENDIF (APIBD_GENERATORSQL_FOUND)

MARK_AS_ADVANCED(
  APIBD_GENERATORSQL_LIBRARY
  APIBD_GENERATORSQL_INCLUDE_DIR
  )
