-- MySQL Script generated by MySQL Workbench
-- lun 21 oct 2019 20:37:03 PDT
-- Model: New Model    Version: 1.1
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sysapp.alpha
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sysapp.alpha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sysapp.alpha` ;
USE `sysapp.alpha` ;

-- -----------------------------------------------------
-- Table `sysapp.alpha`.`Persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysapp.alpha`.`Persons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name1` VARCHAR(45) NOT NULL COMMENT 'Primer nombre',
  `name2` VARCHAR(45) NULL COMMENT 'nombres adicionales',
  `name3` VARCHAR(45) NULL COMMENT 'Herredado del Padre',
  `name4` VARCHAR(45) NULL COMMENT 'Heredado de la Madre',
  `country`  NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysapp.alpha`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysapp.alpha`.`Users` (
  `person` INT NOT NULL,
  `username` VARCHAR(16) NULL,
  `pwTx` VARCHAR(45) NULL,
  `pwMD5` VARCHAR(45) NULL,
  INDEX `fk_Users_Persons_idx` (`person` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Persons`
    FOREIGN KEY (`person`)
    REFERENCES `sysapp.alpha`.`Persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysapp.alpha`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysapp.alpha`.`Company` (
  `id`  NOT NULL,
  `shortName` VARCHAR(40) NULL,
  `fullName` TINYTEXT NULL,
  `rfc` VARCHAR(15) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysapp.alpha`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysapp.alpha`.`Client` (
  `client`  NOT NULL,
  INDEX `fk_Client_Company1_idx` (`client` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Company1`
    FOREIGN KEY (`client`)
    REFERENCES `sysapp.alpha`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysapp.alpha`.`Provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysapp.alpha`.`Provider` (
  `provider`  NOT NULL,
  INDEX `fk_Provider_Company1_idx` (`provider` ASC) VISIBLE,
  CONSTRAINT `fk_Provider_Company1`
    FOREIGN KEY (`provider`)
    REFERENCES `sysapp.alpha`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysapp.alpha`.`Owner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysapp.alpha`.`Owner` (
  `id`  NOT NULL,
  INDEX `fk_Owner_Company1_idx` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Owner_Company1`
    FOREIGN KEY (`id`)
    REFERENCES `sysapp.alpha`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysapp.alpha`.`Catalogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysapp.alpha`.`Catalogs` (
  `id`  NOT NULL,
  `number`  NOT NULL,
  `company`  NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Catalogs_Company1_idx` (`company` ASC) VISIBLE,
  CONSTRAINT `fk_Catalogs_Company1`
    FOREIGN KEY (`company`)
    REFERENCES `sysapp.alpha`.`Company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysapp.alpha`.`Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysapp.alpha`.`Stock` (
  `id`  NOT NULL,
  `item`  NOT NULL,
  `status` SET('wait', 'available', 'out') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Stock_Catalogs1_idx` (`item` ASC) VISIBLE,
  CONSTRAINT `fk_Stock_Catalogs1`
    FOREIGN KEY (`item`)
    REFERENCES `sysapp.alpha`.`Catalogs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysapp.alpha`.`Coins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysapp.alpha`.`Coins` (
  `id`  NOT NULL,
  `code` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysapp.alpha`.`Movements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysapp.alpha`.`Movements` (
  `id`  NOT NULL,
  `pakage` INT(20) NOT NULL,
  `item`  NOT NULL,
  `dt` DATETIME NOT NULL,
  `coin`  NOT NULL,
  `amount` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Movements_Stock1_idx` (`item` ASC) VISIBLE,
  INDEX `fk_Movements_Coins1_idx` (`coin` ASC) VISIBLE,
  CONSTRAINT `fk_Movements_Stock1`
    FOREIGN KEY (`item`)
    REFERENCES `sysapp.alpha`.`Stock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movements_Coins1`
    FOREIGN KEY (`coin`)
    REFERENCES `sysapp.alpha`.`Coins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysapp.alpha`.`Conversion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysapp.alpha`.`Conversion` (
  `id`  NOT NULL,
  `from`  NOT NULL,
  `fromType` DOUBLE NOT NULL COMMENT 'tipo de cambio',
  `to`  NOT NULL,
  `toAmount` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Conversion_Coins1_idx` (`from` ASC) VISIBLE,
  INDEX `fk_Conversion_Coins2_idx` (`to` ASC) VISIBLE,
  CONSTRAINT `fk_Conversion_Coins1`
    FOREIGN KEY (`from`)
    REFERENCES `sysapp.alpha`.`Coins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conversion_Coins2`
    FOREIGN KEY (`to`)
    REFERENCES `sysapp.alpha`.`Coins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysapp.alpha`.`Cashbox`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysapp.alpha`.`Cashbox` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sysapp.alpha`.`ProductionTamalera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysapp.alpha`.`ProductionTamalera` (
  `id`  NOT NULL,
  `pakage` INT(20) NOT NULL,
  `item`  NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Production_Catalogs1_idx` (`item` ASC) VISIBLE,
  CONSTRAINT `fk_Production_Catalogs1`
    FOREIGN KEY (`item`)
    REFERENCES `sysapp.alpha`.`Catalogs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
