SET(TARGET_OBJECT_SUFFIX mysql-c++)

IF (TOOLKIT_CLIENTDB_INCLUDE_DIR)
  # Already in cache, be silent
  SET(TOOLKIT_CLIENTDB_FIND_QUIETLY TRUE)
ENDIF (TOOLKIT_CLIENTDB_INCLUDE_DIR)

FIND_PATH(TOOLKIT_CLIENTDB_INCLUDE_DIR clientdb/clientdb-mysql.hpp
  /usr/include/toolkit
  /usr/local/include/toolkit
)

SET(TOOLKIT_CLIENTDB_NAMES ${TARGET_OBJECT_SUFFIX})
FIND_LIBRARY(TOOLKIT_CLIENTDB_LIBRARIES
  NAMES ${TOOLKIT_CLIENTDB_NAMES}
  PATHS /usr/lib/toolkit/clientdb/ /usr/local/lib/toolkit/clientdb/ /usr/lib/x86_64-linux-gnu/toolkit/clientdb/ /usr/lib/x86_64-linux-gnu/
  PATH_SUFFIXES ${TARGET_OBJECT_SUFFIX}
)

IF(TOOLKIT_CLIENTDB_INCLUDE_DIR AND TOOLKIT_CLIENTDB_LIBRARIES)
  SET(TOOLKIT_CLIENTDB_FOUND TRUE)
  SET(TOOLKIT_CLIENTDB_LIBRARIES ${TOOLKIT_CLIENTDB_LIBRARIES})
ELSE (TOOLKIT_CLIENTDB_INCLUDE_DIR AND TOOLKIT_CLIENTDB_LIBRARIES)
  SET(TOOLKIT_CLIENTDB_FOUND FALSE)
  SET(TOOLKIT_CLIENTDB_LIBRARIES)
ENDIF(TOOLKIT_CLIENTDB_INCLUDE_DIR AND TOOLKIT_CLIENTDB_LIBRARIES)

IF (TOOLKIT_CLIENTDB_FOUND)
  IF (NOT TOOLKIT_CLIENTDB_FIND_QUIETLY)
    MESSAGE(STATUS "Found ${TARGET_OBJECT_SUFFIX}: ${TOOLKIT_CLIENTDB_LIBRARY}")
  ENDIF (NOT TOOLKIT_CLIENTDB_FIND_QUIETLY)
ELSE (TOOLKIT_CLIENTDB_FOUND)
  IF (TOOLKIT_CLIENTDB_FIND_REQUIRED)
    MESSAGE(STATUS "Looked for ${TARGET_OBJECT_SUFFIX} libraries named ${TOOLKIT_CLIENTDB_NAMES}.")
    MESSAGE(FATAL_ERROR "Could NOT find toolkit-client library")
  ENDIF (TOOLKIT_CLIENTDB_FIND_REQUIRED)
ENDIF (TOOLKIT_CLIENTDB_FOUND)

MARK_AS_ADVANCED(
  TOOLKIT_CLIENTDB_LIBRARIES
  TOOLKIT_CLIENTDB_INCLUDE_DIR
  )
