
#  OCTETOS_TOOLKIT_COMMON_CPP_INCLUDE_DIR - where to find clientdb-mysql.hpp, etc.
#  OCTETOS_TOOLKIT_COMMON_CPP_LIBRARIES   - List of libraries when using TK Common.
#  OCTETOS_TOOLKIT_COMMON_CPP_FOUND       - True if TK Common found.

IF (OCTETOS_TOOLKIT_COMMON_CPP_INCLUDE_DIR)
  # Already in cache, be silent
  SET(OCTETOS_TOOLKIT_COMMON_CPP_FIND_QUIETLY TRUE)
ENDIF (OCTETOS_TOOLKIT_COMMON_CPP_INCLUDE_DIR)

IF(${${PROJECT_NAME}_VERSION_STAGE} STREQUAL "snapshot")
	FIND_PATH(OCTETOS_TOOLKIT_COMMON_CPP_INCLUDE_DIR common.hpp
	  $ENV{HOME}/develop/toolkit/common
	)
ELSEIF()
	FIND_PATH(OCTETOS_TOOLKIT_COMMON_CPP_INCLUDE_DIR common.hpp
	  /usr/local/include/octetos/toolkit/common
	  /usr/include/octetos/toolkit/common
	)
ENDIF()

IF(${${PROJECT_NAME}_VERSION_STAGE} STREQUAL "snapshot")
	SET(OCTETOS_TOOLKIT_COMMON_CPP_NAMES octetos-toolkit-common-c++)
	FIND_LIBRARY(OCTETOS_TOOLKIT_COMMON_CPP_LIBRARY
	  NAMES ${OCTETOS_TOOLKIT_COMMON_CPP_NAMES}
	  PATHS $ENV{HOME}/develop/toolkit/common/build-c++
	  PATH_SUFFIXES octetos-toolkit-common-c++
	)
ELSEIF()
	SET(OCTETOS_TOOLKIT_COMMON_CPP_NAMES octetos-toolkit-common-c++)
	FIND_LIBRARY(OCTETOS_TOOLKIT_COMMON_CPP_LIBRARY
	  NAMES ${OCTETOS_TOOLKIT_COMMON_CPP_NAMES}
	  PATHS /usr/lib/octetos/toolkit/common /usr/local/lib/octetos/toolkit/common /usr/lib/x86_64-linux-gnu/octetos/toolkit/common
	  PATH_SUFFIXES octetos-toolkit-common-c++
	)
ENDIF()

IF (OCTETOS_TOOLKIT_COMMON_CPP_INCLUDE_DIR AND OCTETOS_TOOLKIT_COMMON_CPP_LIBRARY)
  SET(OCTETOS_TOOLKIT_COMMON_CPP_FOUND TRUE)
  SET( OCTETOS_TOOLKIT_COMMON_CPP_LIBRARIES ${OCTETOS_TOOLKIT_COMMON_CPP_LIBRARY} )
ELSE (OCTETOS_TOOLKIT_COMMON_CPP_INCLUDE_DIR AND OCTETOS_TOOLKIT_COMMON_CPP_LIBRARY)
  SET(OCTETOS_TOOLKIT_COMMON_CPP_FOUND FALSE)
  SET(OCTETOS_TOOLKIT_COMMON_CPP_LIBRARIES )
ENDIF (OCTETOS_TOOLKIT_COMMON_CPP_INCLUDE_DIR AND OCTETOS_TOOLKIT_COMMON_CPP_LIBRARY)

IF (OCTETOS_TOOLKIT_COMMON_CPP_FOUND)
  IF (NOT OCTETOS_TOOLKIT_COMMON_CPP_FIND_QUIETLY)
    MESSAGE(STATUS "Found Toolkit Common C++: ${OCTETOS_TOOLKIT_COMMON_CPP_LIBRARY}")
  ENDIF (NOT OCTETOS_TOOLKIT_COMMON_CPP_FIND_QUIETLY)
ELSE (OCTETOS_TOOLKIT_COMMON_CPP_FOUND)
  IF (OCTETOS_TOOLKIT_COMMON_CPP_FIND_REQUIRED)
    MESSAGE(STATUS "Looked for Toolkit Common C++ libraries named ${OCTETOS_TOOLKIT_COMMON_CPP_NAMES}.")
    MESSAGE(FATAL_ERROR "Could NOT find Toolkit Common C++ library")
  ENDIF (OCTETOS_TOOLKIT_COMMON_CPP_FIND_REQUIRED)
ENDIF (OCTETOS_TOOLKIT_COMMON_CPP_FOUND)

MARK_AS_ADVANCED(
  OCTETOS_TOOLKIT_COMMON_CPP_LIBRARY
  OCTETOS_TOOLKIT_COMMON_CPP_INCLUDE_DIR
  )
