# - Find mysqlclient
# Find the native MySQL includes and library
#
#  CUNIT_INCLUDE_DIR - where to find mysql.h, etc.
#  CUNIT_LIBRARIES   - List of libraries when using CUnit.
#  CUNIT_FOUND       - True if CUnit found.

IF (CUNIT_INCLUDE_DIR)
  # Already in cache, be silent
  SET(CUNIT_FIND_QUIETLY TRUE)
ENDIF (CUNIT_INCLUDE_DIR)

FIND_PATH(CUNIT_INCLUDE_DIR CUnit.h
  /usr/local/include/CUnit
  /usr/include/CUnit
)

SET(CUNIT_NAMES cunit )
FIND_LIBRARY(CUNIT_LIBRARY
  NAMES ${CUNIT_NAMES}
  PATHS /usr/lib /usr/local/lib /usr/lib/x86_64-linux-gnu
  PATH_SUFFIXES cunit
)

IF (CUNIT_INCLUDE_DIR AND CUNIT_LIBRARY)
  SET(CUNIT_FOUND TRUE)
  SET( CUNIT_LIBRARIES ${CUNIT_LIBRARY} )
ELSE (CUNIT_INCLUDE_DIR AND CUNIT_LIBRARY)
  SET(CUNIT_FOUND FALSE)
  SET( CUNIT_LIBRARIES )
ENDIF (CUNIT_INCLUDE_DIR AND CUNIT_LIBRARY)

IF (CUNIT_FOUND)
  IF (NOT CUNIT_FIND_QUIETLY)
    MESSAGE(STATUS "Found Cunit: ${CUNIT_LIBRARY}")
  ENDIF (NOT CUNIT_FIND_QUIETLY)
ELSE (CUNIT_FOUND)
  IF (CUNIT_FIND_REQUIRED)
    MESSAGE(STATUS "Looked for CUnit libraries named ${CUNIT_NAMES}.")
    MESSAGE(FATAL_ERROR "Could NOT find CUnit library")
  ENDIF (CUNIT_FIND_REQUIRED)
ENDIF (CUNIT_FOUND)

MARK_AS_ADVANCED(
  CUNIT_LIBRARY
  CUNIT_INCLUDE_DIR
  )
