#SET(CMAKE_FIND_LIBRARY_SUFFIXES .a .so)
IF (OCTETOS_DB_POSTGRESQL_INCLUDE_DIR)
  # Already in cache, be silent
  SET(OCTETOS_DB_POSTGRESQL_FIND_QUIETLY TRUE)
ENDIF (OCTETOS_DB_POSTGRESQL_INCLUDE_DIR)


FIND_PATH(OCTETOS_DB_POSTGRESQL_INCLUDE_DIR db/clientdb-postgresql.hh
        /usr/local/include/octetos
        /usr/include/octetos
)


FIND_LIBRARY(OCTETOS_DB_LIBRARY liboctetos-db.so
        NAMES ${OCTETOS_DB_NAMES}
        PATHS /lib /lib64 /lib32 /usr/local/lib/ /usr/lib/x86_64-linux-gnu/
        PATH_SUFFIXES octetos-db
)
FIND_LIBRARY(OCTETOS_DB_POSTGRESQL_LIBRARY
        NAMES liboctetos-db-postgresql.so
        PATHS /lib /lib64 /lib32 /usr/local/lib/ /usr/lib/x86_64-linux-gnu/
        PATH_SUFFIXES octetos-db-postgresql
)
FIND_LIBRARY(LIBPQ_LIBRARY
        NAMES libpq.so
        PATHS /lib /lib64 /lib32 /usr/local/lib/ /usr/lib/x86_64-linux-gnu/
        PATH_SUFFIXES pq
)


IF (OCTETOS_DB_POSTGRESQL_INCLUDE_DIR)
  SET(OCTETOS_DB_POSTGRESQL_FOUND TRUE)
  SET(OCTETOS_DB_POSTGRESQL_LIBRARIES ${LIBPQ_LIBRARY} ${OCTETOS_DB_LIBRARY} ${OCTETOS_DB_POSTGRESQL_LIBRARY} )
ELSE (OCTETOS_DB_POSTGRESQL_INCLUDE_DIR)
  SET(OCTETOS_DB_POSTGRESQL_FOUND FALSE)
  SET(OCTETOS_DB_POSTGRESQL_LIBRARIES )
ENDIF (OCTETOS_DB_POSTGRESQL_INCLUDE_DIR)

IF (OCTETOS_DB_POSTGRESQL_FOUND)
  IF (NOT OCTETOS_DB_POSTGRESQL_FIND_QUIETLY)
    MESSAGE(STATUS "Found DB PostgreSQL de Octetos: ${LIBPQ_LIBRARY},${OCTETOS_DB_LIBRARY},${OCTETOS_DB_POSTGRESQL_LIBRARY}")
  ENDIF (NOT OCTETOS_DB_POSTGRESQL_FIND_QUIETLY)
ELSE (OCTETOS_DB_POSTGRESQL_FOUND)
  IF (OCTETOS_DB_POSTGRESQL_FIND_REQUIRED)
    MESSAGE(STATUS "Looked for Toolkit octeos-db-postgresql C++ libraries named ${OCTETOS_DB_POSTGRESQL_NAMES}.")
    MESSAGE(FATAL_ERROR "Could NOT find octeos-db-postgresql library")
  ENDIF (OCTETOS_DB_POSTGRESQL_FIND_REQUIRED)
ENDIF (OCTETOS_DB_POSTGRESQL_FOUND)

MARK_AS_ADVANCED(
  OCTETOS_DB_POSTGRESQL_LIBRARY
  OCTETOS_DB_POSTGRESQL_INCLUDE_DIR
  )
#SET(CMAKE_FIND_LIBRARY_SUFFIXES .so)
