#  OCTETOS_CORE_INCLUDE_DIR - where to find file.
#  OCTETOS_CORE_LIBRARIES   - List of libraries when using TK Common.
#  OCTETOS_CORE_FOUND       - True if TK Common found.

#SET(CMAKE_FIND_LIBRARY_SUFFIXES .a .so)

IF (OCTETOS_CORE_INCLUDE_DIR)
  # Already in cache, be silent
  SET(OCTETOS_CORE_FIND_QUIETLY TRUE)
ENDIF (OCTETOS_CORE_INCLUDE_DIR)



FIND_PATH(OCTETOS_CORE_INCLUDE_DIR core/Object.hh
        /usr/local/include/octetos
        /usr/include/octetos
    )

FIND_LIBRARY(OCTETOS_CORE_LIBRARY
NAMES liboctetos-core.so
PATHS /lib /lib64 /lib32 /usr/lib /usr/local/lib /usr/lib/x86_64-linux-gnu
PATH_SUFFIXES octetos-core )   
 


IF (OCTETOS_CORE_INCLUDE_DIR)
  SET(OCTETOS_CORE_FOUND TRUE)
  SET(OCTETOS_CORE_LIBRARIES ${OCTETOS_CORE_LIBRARY} )
ELSE (OCTETOS_CORE_INCLUDE_DIR)
  SET(OCTETOS_CORE_FOUND FALSE)
  SET(OCTETOS_CORE_LIBRARIES )
ENDIF (OCTETOS_CORE_INCLUDE_DIR)

IF (OCTETOS_CORE_FOUND)
  IF (NOT OCTETOS_CORE_FIND_QUIETLY)
    MESSAGE(STATUS "Found Octetos Core:  ${OCTETOS_CORE_LIBRARY}")
  ENDIF (NOT OCTETOS_CORE_FIND_QUIETLY)
ELSE (OCTETOS_CORE_FOUND)
  IF (OCTETOS_CORE_FIND_REQUIRED)
    MESSAGE(STATUS "Looked for Octetos Core C++ libraries.")
    MESSAGE(FATAL_ERROR "Could NOT find Octetos Core C++ library")
  ENDIF (OCTETOS_CORE_FIND_REQUIRED)
ENDIF (OCTETOS_CORE_FOUND)

MARK_AS_ADVANCED(
  OCTETOS_CORE_LIBRARY
  OCTETOS_CORE_INCLUDE_DIR
  )
#SET(CMAKE_FIND_LIBRARY_SUFFIXES .so)
