
IF (OCTETOS_CORE_DB_MYSQL_CC_INCLUDE_DIR)
  # Already in cache, be silent
  SET(OCTETOS_CORE_DB_MYSQL_CC_FIND_QUIETLY TRUE)
ENDIF (OCTETOS_CORE_DB_MYSQL_CC_INCLUDE_DIR)

if("${APIDB_VERSION_STAGE}" STREQUAL "developing" )  
    FIND_PATH(OCTETOS_CORE_DB_MYSQL_CC_INCLUDE_DIR db/clientdb.hh
        $ENV{HOME}/develop/octetos-db/Debug/src
    )
    #MESSAGE(STATUS "OCTETOS_CORE_DB_MYSQL_CC_INCLUDE_DIR: ${OCTETOS_CORE_DB_MYSQL_CC_INCLUDE_DIR}")
    SET(OCTETOS_CORE_DB_MYSQL_CC_NAMES octetos-db-mysql-cc)
    FIND_LIBRARY(OCTETOS_CORE_DB_MYSQL_CC_LIBRARY
        NAMES ${OCTETOS_CORE_DB_MYSQL_CC_NAMES}
        PATHS $ENV{HOME}/develop/octetos-db/Debug/src
        PATH_SUFFIXES octetos-db-mysql-cc
    )
    #MESSAGE(STATUS "OCTETOS_CORE_DB_MYSQL_CC_LIBRARY: ${OCTETOS_CORE_DB_MYSQL_CC_LIBRARY}")
else()
    FIND_PATH(OCTETOS_CORE_DB_MYSQL_CC_INCLUDE_DIR db/clientdb.hh
        /usr/local/include/octetos
        /usr/include/octetos
    )
    SET(OCTETOS_CORE_DB_MYSQL_CC_NAMES octetos-db-mysql-cc)
    FIND_LIBRARY(OCTETOS_CORE_DB_MYSQL_CC_LIBRARY
        NAMES ${OCTETOS_CORE_DB_MYSQL_CC_NAMES}
        PATHS /lib /lib64 /lib32 /usr/local/lib/ /usr/lib/x86_64-linux-gnu/
        PATH_SUFFIXES octetos-db-mysql-cc
    )
endif()



IF (OCTETOS_CORE_DB_MYSQL_CC_INCLUDE_DIR AND OCTETOS_CORE_DB_MYSQL_CC_LIBRARY)
  SET(OCTETOS_CORE_DB_MYSQL_CC_FOUND TRUE)
  SET(OCTETOS_CORE_DB_MYSQL_CC_LIBRARIES ${OCTETOS_CORE_DB_MYSQL_CC_LIBRARY} )
ELSE (OCTETOS_CORE_DB_MYSQL_CC_INCLUDE_DIR AND OCTETOS_CORE_DB_MYSQL_CC_LIBRARY)
  SET(OCTETOS_CORE_DB_MYSQL_CC_FOUND FALSE)
  SET(OCTETOS_CORE_DB_MYSQL_CC_LIBRARIES )
ENDIF (OCTETOS_CORE_DB_MYSQL_CC_INCLUDE_DIR AND OCTETOS_CORE_DB_MYSQL_CC_LIBRARY)

IF (OCTETOS_CORE_DB_MYSQL_CC_FOUND)
  IF (NOT OCTETOS_CORE_DB_MYSQL_CC_FIND_QUIETLY)
    MESSAGE(STATUS "Found octetos-db-mysql C++: ${OCTETOS_CORE_DB_MYSQL_CC_LIBRARY}: ${OCTETOS_TOOLKIT_COMMON_CPP_INCLUDE_DIR}")
  ENDIF (NOT OCTETOS_CORE_DB_MYSQL_CC_FIND_QUIETLY)
ELSE (OCTETOS_CORE_DB_MYSQL_CC_FOUND)
  IF (OCTETOS_CORE_DB_MYSQL_CC_FIND_REQUIRED)
    MESSAGE(STATUS "Looked for Toolkit octeos-db-mysql C++ libraries named ${OCTETOS_CORE_DB_MYSQL_CC_NAMES}.")
    MESSAGE(FATAL_ERROR "Could NOT find octeos-db-mysql library")
  ENDIF (OCTETOS_CORE_DB_MYSQL_CC_FIND_REQUIRED)
ENDIF (OCTETOS_CORE_DB_MYSQL_CC_FOUND)

MARK_AS_ADVANCED(
  OCTETOS_CORE_DB_MYSQL_CC_LIBRARY
  OCTETOS_CORE_DB_MYSQL_CC_INCLUDE_DIR
  )
