SET(TARGET_OBJECT_SUFFIX tar)

IF (TAR_INCLUDE_DIR)
  # Already in cache, be silent
  SET(TAR_FIND_QUIETLY TRUE)
ENDIF (TAR_INCLUDE_DIR)

FIND_PATH(TOOLKIT_COMMON_INCLUDE_DIR libtar.h
  /usr/include
  /usr/local/include
)

SET(TAR_NAMES ${TARGET_OBJECT_SUFFIX})
FIND_LIBRARY(TAR_LIBRARY
  NAMES ${TAR_NAMES}
  PATHS /usr/lib/ /usr/local/lib/ /usr/lib/x86_64-linux-gnu/ /usr/lib/x86_64-linux-gnu/
  PATH_SUFFIXES ${TARGET_OBJECT_SUFFIX}
)

IF (TAR_INCLUDE_DIR AND TAR_LIBRARY)
  SET(TAR_FOUND TRUE)
  SET(TAR_LIBRARIES ${TAR_LIBRARY} )
ELSE (TAR_INCLUDE_DIR AND TAR_LIBRARY)
  SET(TAR_FOUND FALSE)
  SET(TAR_LIBRARIES )
ENDIF (TAR_INCLUDE_DIR AND TAR_LIBRARY)

IF (TAR_FOUND)
  IF (NOT TAR_FIND_QUIETLY)
    MESSAGE(STATUS "Found ${TARGET_OBJECT_SUFFIX}: ${TAR_LIBRARY}")
  ENDIF (NOT TAR_FIND_QUIETLY)
ELSE (TAR_FOUND)
  IF (TAR_FIND_REQUIRED)
    MESSAGE(STATUS "Looked for ${TARGET_OBJECT_SUFFIX} libraries named ${TAR_NAMES}.")
    MESSAGE(FATAL_ERROR "Could NOT find ${TARGET_OBJECT_SUFFIX} library")
  ENDIF (TAR_FIND_REQUIRED)
ENDIF (TAR_FOUND)

MARK_AS_ADVANCED(
  TAR_LIBRARY
  TAR_INCLUDE_DIR
  )
